services:
  db:
    image: postgres:17.2
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    mem_limit: 500m
    networks:
      - backend

  goodjob:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: bash -c "bin/rails db:migrate && bundle exec good_job start"
    depends_on:
      - db
    volumes:
      - ./config/credentials:/rails/config/credentials
      - rails_log:/rails/log
      - rails_tmp:/rails/tmp
      - rails_storage:/rails/storage
    env_file:
      - .env
    environment:
      - RAILS_ENV=production
    networks:
      - backend
    mem_limit: 500m

  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - ./config/credentials:/rails/config/credentials
      - rails_log:/rails/log
      - rails_storage:/rails/storage
      - rails_tmp:/rails/tmp
    env_file:
      - ".env"
    ports:
      - "8081:3000"
    depends_on:
      - db
      - goodjob
    environment:
      - GUI_AVAILABLE=false
      - RAILS_ENV=production
    mem_limit: 1g
    networks:
      - backend

volumes:
  pgdata: {}
  rails_log:
  rails_storage:
  rails_tmp:

networks:
  backend:

