version: '3.8'  # Add this line at the top

services:
  # PostgreSQL container
  db:
    image: postgres:17.2
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    mem_limit: 500m
    networks:
      - backend

  # GoodJob container
  goodjob:
    build:
      context: .
      args:
        - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    command: bash -c "bin/rails db:migrate && bundle exec good_job start"
    depends_on:
      - db
    volumes:
      - .:/rails
    env_file:
      - .env
    environment:
      - RAILS_ENV=development
    networks:
      - backend
    mem_limit: 500m

  # Webserver container
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails
      - storage:/rails/storage
    env_file:
      - ".env"
    ports:
      - "3002:3000"
    depends_on:
      - db
      - goodjob
    environment:
      - GUI_AVAILABLE=false
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    mem_limit: 1g
    stdin_open: true
    tty: true
    networks:
      - backend

volumes:
  pgdata: {}
  storage: {}

networks:
  backend:
    driver: bridge
